name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.33

      - name: Install dependencies
        run: bun install

      - name: Run unit tests
        run: bun run test

      - name: Run linter
        run: bun run lint

      - name: Check licenses
        run: |
          npx license-checker --onlyAllow "MIT;Apache-2.0;ISC;BSD-2-Clause;Python-2.0;CC-BY-4.0;BSD-3-Clause;BlueOak-1.0.0;CC0-1.0;0BSD;CC-BY-3.0"
          if [ $? -ne 0 ]; then
            echo "License check failed!"
            exit 1
          fi

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.33

      - name: Build project
        run: bun run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # - name: Git describe
      #   id: ghd
      #   uses: proudust/gh-describe@v2.0.1

      # - name: Run Version Check
      #   run: |
      #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     cd scripts
      #     chmod +x ./check_version.sh  # Ensure the script is executable
      #     current_version=$(node -p "require('../package.json').version")
      #     echo "Current version: $current_version"
      #     last_version="${{ steps.ghd.outputs.tag }}"
      #     echo "Last released version: $last_version"
      #     ./check_version.sh $current_version $last_version

      - name: Deploy to GitHub Pages
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "GITHUB_TOKEN is not set. Deployment cannot proceed."
            exit 1
          fi
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -t --cname "tickleiste.tklic.de" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
