name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - synchronize # Trigger when new commits are pushed to the PR
      - opened # Trigger when the PR is opened n  
      - reopened # Trigger when the PR is reopened

jobs:
  test:
    uses: ./.github/workflows/checks_callable.yml
