name: Build and Deploy

# on: workflow_dispatch
on:
  push:
    branches:
      - main

jobs:
  # test:
  #   uses: ./.github/workflows/checks_callable.yml

  build:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.33

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: ./build
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Restore build artifacts from cache
        uses: actions/cache@v4
        with:
          path: ./build
          key: ${{ runner.os }}-build-${{ github.sha }}
      # - name: Git describe
      #   id: ghd
      #   uses: proudust/gh-describe@v2.0.1

      # - name: Run Version Check
      #   run: |
      #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     cd scripts
      #     chmod +x ./check_version.sh  # Ensure the script is executable
      #     current_version=$(node -p "require('../package.json').version")
      #     echo "Current version: $current_version"
      #     last_version="${{ steps.ghd.outputs.tag }}"
      #     echo "Last released version: $last_version"
      #     ./check_version.sh $current_version $last_version

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -t --cname "tickleiste.tklic.de" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
