name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.33

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Deploy to GitHub Pages
      run: bun run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
