name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.33

      - name: Install dependencies
        run: bun install

      - name: Run unit tests
        run: bun run test

      - name: Run linter
        run: bun run test

      - name: Git describe
        id: ghd
        uses: proudust/gh-describe@v2

      - name: Run Version Check
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          cd scripts
          chmod +x ./check_version.sh  # Ensure the script is executable
          current_version=$(node -p "require('../package.json').version")
          echo "Current version: $current_version"
          last_version=steps.ghd.outputs.tag
          echo "Last released version: $last_version"
          ./check_version.sh $current_version $last_version

      - name: Build project
        run: bun run build

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
